server:
  port: 1001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: cloud-user
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6179
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 5000
    password: 25251325
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.229.177.240:3306/blog?characterEncoding=utf-8
  banner:
    location: com\jason\server\banner.txt




